repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - '--args=--lockfile=false'
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
      ##########################################################################
      # https://www.terraform.io/language/expressions/version-constraints
      ##########################################################################
      # Reusable modules should constrain only their minimum allowed versions of
      # Terraform and providers, such as >= 0.12.0. This helps avoid known
      # incompatibilities, while allowing the user of the module flexibility to
      # upgrade to newer versions of Terraform without altering the module.
      ##########################################################################
      - id: tfupdate
        name: Autoupdate Terraform version
        args:
          - --args=terraform
          - --args=--version=>=0.13.1
      - id: tfupdate
        name: Autoupdate AWS provider version
        args:
          - --args=provider aws
          - --args=--version=>=3.63.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
